<div class='banner_wrapper col-lg-12 clearfix'>
    <div class='images_wrapper'>
        <div class='images_container clearfix' style='width:300%;'>
            <img src='pages/default/resources/images/banner-1.jpg' class='pull-left' style='width:33.33%'>
            <img src='pages/default/resources/images/banner-2.jpg' class='pull-left' style='width:33.33%'>
            <img src='pages/default/resources/images/banner-3.png' class='pull-left' style='width:33.33%'>
        </div>
    </div>
    <div class='marker_wrapper'>
        <div class='marker_container'>
            <div class='marker active'></div>
            <div class='marker'></div>
            <div class='marker'></div>
        </div>
    </div>
    <div class='text_banner fix_wid'>
        <div class='col-lg-10 col-lg-offset-1'>
            <div class='text_container var_wid clearfix'>
                <div class='one_item pull-left clearfix'>
                    <div class='pull-left'>
                        <div class='heading'>
                            We promise best smartphone deals ever
                            <div class='subheading'>
                                With physical stock storage, we ensure fastest delivery
                            </div>
                        </div>
                    </div>
                    <a href='<?php echo App::_route('default/products',true)?>#bestMobileDeals' class='theme-btn-big pull-right theme-btn-uc'>Read more</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class='brief_wrapper about_us clearfix'>
    <div class='one_row col-xs-12 col-sm-10 col-md-10 col-lg-10 col-sm-offset-1 col-md-offset-1 col-lg-offset-1' id='verified-member'>
        <h2 style='margin-top:50px'>Verified member of B2B portals
            <span class='subheading'>
                We are a verified member of all B2B portals
            </span>
        </h2>
        <div class='para clearfix'>
            <div class='col-xs-12 col-sm-4 col-md-3 col-lg-3 logo_wrapper'>
                <div class='tick-left'></div>
                <img src='<?php echo level.'pages/default/resources/images/handelot-logo.jpg'?>'>
                <img src='<?php echo level.'pages/default/resources/images/gsmexchange.gif'?>'>
            </div>
            <div class='col-xs-12 col-sm-8 col-md-9 col-lg-9 desc'>
                <p>
                We are one of the leading mobile handset trading company in Dubai. We are based in the centre of mobile market at Diera Dubai.<p>We are also a verified <b>premium member</b> of B2B portals like <a href='//www.gsmexchange.com'>GSMExchange</a> and <a href='//www.handelot.com'>Handelot</a> and we have a very clean and professional record of trading. That ensures you that you're doing business with a verified company. In case you have any doubts about us, you're free to reach us or our clients!
            </div>
        </div>
    </div>
    
    <div class='one_row col-xs-12 col-sm-10 col-md-10 col-lg-10 col-sm-offset-1 col-md-offset-1 col-lg-offset-1' id='worldwide'>
        <h2>Worldwide business
            <span class='subheading'>
                International traders and worldwide distributors
            </span>
        </h2>
        <div class='para clearfix'>
            <div class='col-xs-12 col-sm-8 col-md-9 col-lg-9 desc'>
                <p>
                Within a short time span of 4 years, with a clean and professional record of trading, We have placed ourselves in one of the leading mobile handset trading companies in Dubai. Along with this, we have strong business relationship with leading International traders, worldwide distributors and retailers of mobiles in UAE.<p>Our distributors are spread over countries, ensuring that your orders will never hang up in between processes. We hold stocks in our own inventory which makes sure that orders are processed faster and deliveries are made at the earliest.
            </div>
            <div class='col-xs-12 col-sm-4 col-md-3 col-lg-3 rounded_box'>
                <img src='<?php echo level.'pages/default/resources/images/authentic.jpg'?>' style='max-width:70%; margin:0 auto; position:relative;'>
            </div>
        </div>
    </div>
</div>
<img src='<?php echo level.'pages/default/resources/images/banner-about-us.png'?>' style='width:100%'>

<!--div class='brief_wrapper about_us clearfix'>
    <div class='one_row col-xs-12 col-sm-10 col-md-10 col-lg-10 col-sm-offset-1 col-md-offset-1 col-lg-offset-1' style='margin-top:50px' id='our-team'>
        <h2>Excellence of Years
            <span class='subheading'>
                Our awesomeness comes from some awesome members!
            </span>
        </h2>
        <div class='para clearfix'>
            <div class='col-xs-12 col-sm-4 col-md-4 col-lg-3 intro'>
                <div class='rounded_box pic'>
                    <img src='<?php echo level.'pages/default/resources/images/me.jpg'?>'>
                </div>
                <h3 class='name'>Syed Ali</h3>
                <div class='subheading'>
                    Purchase Manager
                </div>
            </div>
            <div class='col-xs-12 col-sm-4 col-md-4 col-lg-3 intro'>
                <div class='rounded_box pic'>
                    <img src='<?php echo level.'pages/default/resources/images/me.jpg'?>'>
                </div>
                <h3 class='name'>Syed Ali</h3>
                <div class='subheading'>
                    Purchase Manager
                </div>
            </div>
            <div class='col-xs-12 col-sm-4 col-md-4 col-lg-3 intro'>
                <div class='rounded_box pic'>
                    <img src='<?php echo level.'pages/default/resources/images/me.jpg'?>'>
                </div>
                <h3 class='name'>Syed Ali</h3>
                <div class='subheading'>
                    Purchase Manager
                </div>
            </div>
            <div class='col-xs-12 col-sm-4 col-md-4 col-lg-3 intro'>
                <div class='rounded_box pic'>
                    <img src='<?php echo level.'pages/default/resources/images/me.jpg'?>'>
                </div>
                <h3 class='name'>Syed Ali</h3>
                <div class='subheading'>
                    Purchase Manager
                </div>
            </div>
        </div>
    </div>
</div-->