<div class='upper_footer clearfix'>
    <div>Connect with us here:</div>
    <div>
        <a class='social_wrapper fb' href="http://facebook.com/iamsayed" target="_blank">
            <span class='fb icon icon-facebook'></span>
        </a>
        <a class='social_wrapper twitter' href="http://twitter.com/eternalsayed" target="_blank">
            <span class='fb icon icon-twitter'></span>
        </a>
        <a class='social_wrapper linkedin' target="_blank">
            <span class='fb icon icon-linkedin'></span>
        </a>
    </div>
</div>
<div class='lower_footer clearfix'>
	<div class='pull-left col-sm-offset-1 col-md-offset-1 col-lg-offset-1'>
		&copy <?php echo date('Y').' '.SITE_NAME?>
	</div>
	<div class='pull-right' style='margin-right:10%;'>
		Made by: <a href="https://www.facebook.com/convexsys?utm_source=simran" style="color:inherit;">Convexsys Pvt. Ltd.</a>
	</div>
</div>