<div class='ceditor-list sidebar col-sm-3 col-md-3 col-lg-2'>
	<h4 class='editor-label'>Code Editor
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
    </h4>
    <ul class="dropdown-menu">
        <li>Page
        <li>Page
        <li>Page
    </ul>
	<div class='list-container'>
    <?php 
	$page = sRequest::_get('pagename',CURRENT_PAGE);
	Page::getDirectories($page,true); ?>
	</div>
</div>
<div class='col-sm-9 col-md-9 col-lg-9 col-sm-offset-3 col-md-offset-3  col-lg-offset-3 main page-list'>
</div>